### ISSUE TITLE
Build issue - due to ... potential "[..]Javascript will need refactoring[..]" ?

### ISSUE THREAD

**Issue by fenix011** [brennanbrown/enjoyment-work#3] opened 2021-03-08 08:51 UTC
I'm not deploying in Netlify but in CloudCannon, ... and i'm having a build issue there, i reported them :

```
Hi CloudCannon,

While importing a (Jekyll) repo i get

...


Generating...

Jekyll Feed: Generating feed for posts

------------------------------------------------
Jekyll 4.0.0 Please append `--trace` to the `build` command for any additional information or backtrace.

------------------------------------------------

x Your build failed, make an update and try again.
```
Their answer mentions a potential JS cause of... i'm just reproducing it here below:

```
...
I have taken a look in to your site and the error seems to be coming from an asynchronous function in

assets/js/contextmenu.js

I commented out the async function getRelatedHTML and

function showRelated and the site built. I believe this Javascript will need refactoring and looked in to.
```
FYI, 

ThX !

**Comment by brennanbrown** [comment] 2021-03-08 20:56
Hi! I was able to reproduce the error successfully, this is the output I received from the command line:

```bash
bundler: failed to load command: jekyll (/usr/local/__bundle/ruby/2.5.0/bin/jekyll)/usr/local/__bundle/ruby/2.5.0/gems/uglifier-4.2.0/lib/uglifier.rb:291:in 
`parse_result': Unexpected token: keyword (function). 
To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true). (Uglifier::Error)
```

It looks like the problem is just with the ES6 syntax. I'll look into this further.

**Comment by brennanbrown** [comment] 2021-03-08 21:00
This seems to be the solution: https://github.com/rails/webpacker/issues/1285

However, I will need to investigate how to change the configurations, as it's built-in to Jekyll itself.

Maybe something like this? https://github.com/envygeeks/jekyll-assets

**Comment by brennanbrown** [comment] 2021-03-08 21:07
Okay, instead I just converted the ES6 syntax, and it is fixed on my build! 

![Screen Shot 2021-03-08 at 2 07 11 PM](https://user-images.githubusercontent.com/60280949/110382059-9e196680-8017-11eb-928f-8458f9ae4e88.png)

**Closed as completed by brennanbrown** 2021-03-08 21:07 UTC
Labels: bug

**Comment by fenix011** [comment] 2021-03-10 10:20
:-) great !
